# Generated by Django 3.0.7 on 2020-06-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='service',
            name='street_address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='zip_code',
            field=models.CharField(default='', max_length=16),
        ),
    ]
