# Generated by Django 3.0.7 on 2020-06-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200623_0109"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="color",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("teal", "Teal"),
                    ("orange", "Orange"),
                    ("purple", "Purple"),
                    ("green", "Green"),
                    ("indigo", "Indigo"),
                    ("yellow", "Yellow"),
                    ("gray", "Gray"),
                ],
                default="gray",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="icon",
            field=models.CharField(
                default="",
                help_text=(
                    "Upload a 300px x 300px to the 'static' directory. Add file path"
                    " here."
                ),
                max_length=128,
            ),
        ),
    ]
