# Generated by Django 3.0.7 on 2020-06-24 02:06

from django.db import migrations


def add_categories(apps, schema_editor):
    """Create the initial categories."""
    ServiceCategory = apps.get_model("core", "ServiceCategory")
    categories = [
        ServiceCategory(
            name="Basic Needs",
            slug="basic-needs",
            description="Food, Clothing, Hygiene, and Transportation",
            icon="categories/basic.png",
            color="teal",
        ),
        ServiceCategory(
            name="Health",
            slug="health",
            description="Services, Support, and Counseling",
            icon="categories/health.png",
            color="orange",
        ),
        ServiceCategory(
            name="Shelter + Centers",
            slug="shelter-centers",
            description="Temporary Shelters, Host Homes, and Other Housing Needs",
            icon="categories/shelter.png",
            color="purple",
        ),
        ServiceCategory(
            name="Money + Legal",
            slug="money-legal",
            description="Advocacy and Counseling",
            icon="categories/money-legal.png",
            color="green",
        ),
        ServiceCategory(
            name="Education + Jobs",
            slug="education-jobs",
            description="Services, Support, and Counseling",
            icon="categories/education-jobs.png",
            color="indigo",
        ),
        ServiceCategory(
            name="Activities + Experiences",
            slug="activities-experiences",
            description=(
                "Funding and Services for Social and Emotional Needs Across a Spectrum"
                " of Interests and Activities"
            ),
            icon="categories/activities-experiences.png",
            color="yellow",
        ),
    ]
    ServiceCategory.objects.bulk_create(categories)


def remove_categories(apps, schema_editor):
    """Remove the activities created by this data migration."""
    ServiceCategory = apps.get_model("core", "ServiceCategory")
    ServiceCategory.objects.filter(
        slug__in=[
            "basic-needs",
            "health",
            "shelter-centers",
            "money-legal",
            "education-jobs",
            "activities-experiences",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200624_0204"),
    ]

    operations = [migrations.RunPython(add_categories, remove_categories)]
