# Generated by Django 3.0.7 on 2020-06-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_initial_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="organization_name",
            field=models.CharField(default="", max_length=128),
        ),
    ]
